# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-config
data:
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/auctiondb"
  REDIS_URL: "redis://redis-service:6379"
