# service.yml
apiVersion: v1
kind: Service
metadata:
  name: auction-api-service
spec:
  selector:
    app: auction-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
