# service.yml
apiVersion: v1
kind: Service
metadata:
  name: auction-api-service
spec:
  selector:
    app: auction-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Matches containerPort in deployment
  type: LoadBalancer